Add files via upload

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1564,7 +1564,7 @@ exit 0' >$RCLOCAL
 				clear
 				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
 				echo ""
-				fun_WebSocketoff() {
+				fun_wssocksoff() {
 					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
 						screen -r -S "$pidproxy" -X quit
 					done
@@ -1576,7 +1576,7 @@ exit 0' >$RCLOCAL
 				}
 				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET\033[1;33m"
 				echo ""
-				fun_bar 'fun_WebSocketoff'
+				fun_bar 'fun_wssocksoff'
 				echo ""
 				echo -e "\033[1;32mWEBSOCKET DESATIVADO COM SUCESSO!\033[1;33m"
 				sleep 3
@@ -1595,7 +1595,7 @@ exit 0' >$RCLOCAL
 					fun_conexao
 				}
 				verif_ptrs $porta
-				fun_iniWebSocket() {
+				fun_iniwssocks() {
 					sleep 1
 					screen -dmS ws python /etc/SSHPlus/wsproxy.py $porta
 					[[ $(grep -wc "wsproxy.py" /etc/autostart) = '0' ]] && {
@@ -1608,18 +1608,17 @@ exit 0' >$RCLOCAL
 				echo ""
 				echo -e "\033[1;32mINICIANDO O WEBSOCKET\033[1;33m"
 				echo ""
-				fun_bar 'fun_iniWebSocket'
+				fun_bar 'fun_iniwssocks'
 				echo ""
-				echo -e "\033[1;32WebSocket ATIVADO COM SUCESSO\033[1;33m"
+				echo -e "\033[1;32WSSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
 			fi
-			
-			
-	elif [[ "$resposta" = '3' ]]; then
+
+elif [[ "$resposta" = '3' ]]; then
 		clear
 		if ps x | grep -w WebSocket | grep -v grep 1>/dev/null 2>/dev/null; then
-		echo -e "\E[41;1;37m          WEBSOCKET SECURITY              \E[0m"
+		echo -e "\E[41;1;37m           WEBSOCKET SECURITY               \E[0m"
 				echo ""
 				fun_wsswsocksoff() { 
 					pkill WebSocket
@@ -1635,62 +1634,6 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
 				echo ""
 				fun_bar 'fun_wsswsocksoff'
-				echo ""
-				echo -e "\033[1;32mWEBSOCKET SECURITY DESATIVADO COM SUCESSO!\033[1;33m"
-				
-				fun_socks
-			else
-		echo -e "\E[44;1;37m          WEBSOCKET SECURITY              \E[0m"
-				echo ""
-				echo "$(echo -e "\033[1;32mPORTA UTILIZADA 80 \033[1;37m")"
-				[[ -z "porta" ]] && {
-					echo ""
-					echo -e "\033[1;31mPorta invalida!"
-					
-				fun_socks
-				}
-				verif_ptrs $porta
-				fun_iniwssocks() {
-					sleep 1
-					screen -dmS novoWS /etc/SSHPlus/WebSocket 
-					[[ $(grep -wc "WebSocket" /etc/autostart) = '0' ]] && {
-						echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:80" >>/etc/autostart
-					} || {
-						sed -i '/WebSocket/d' /etc/autostart
-						echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:80" >>/etc/autostart
-					}
-				}
-				echo ""
-				echo -e "\033[1;32mINICIANDO O WEBSOCKET SECURITY\033[1;33m"
-				echo ""
-				fun_bar 'fun_iniwssocks'
-				echo ""
-				echo -e "\033[1;32WEBSOCKET SECURITY ATIVADO COM SUCESSO\033[1;33m"
-				
-				fun_socks
-			fi
-			
-			
-
-elif [[ "$resposta" = '3.2' ]]; then
-		clear
-		if ps x | grep -w WebSocket | grep -v grep 1>/dev/null 2>/dev/null; then
-		echo -e "\E[41;1;37m           WEBSOCKET SECURITY               \E[0m"
-				echo ""
-				fun_WebSocketoff() { 
-					pkill WebSocket
-					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
-						screen -r -S "$WebSocket" -X quit
-					done
-					[[ $(grep -wc "WebSocket" /etc/autostart) != '0' ]] && {
-						sed -i '/WebSocket/d' /etc/autostart
-					}
-					sleep 1
-					screen -wipe >/dev/null
-				}
-				echo -e "\033[1;32mDESATIVANDO O WEBSOCKET SECURITY\033[1;33m"
-				echo ""
-				fun_bar 'fun_WebSocketoff'
 				echo ""
 				echo -e "\033[1;32mWEBSOCKET SECURITY DESATIVADO COM SUCESSO!\033[1;33m"
 				
@@ -1712,20 +1655,20 @@ elif [[ "$resposta" = '3.2' ]]; then
 				fun_socks
 				}
 				verif_ptrs $porta
-				fun_iniWebSocket() {
+				fun_iniwssocks() {
 					sleep 1
-					screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:$(cat /etc/mamalista)					
+				screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:$(cat /etc/mamalista)					
 					[[ $(grep -wc "WebSocket" /etc/autostart) = '0' ]] && {
-						echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+				echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:$(cat /etc/mamalista)
 					} || {
 						sed -i '/WebSocket/d' /etc/autostart
-						echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+				echo -e "screen -dmS novoWS /etc/SSHPlus/WebSocket -proxy_port 0.0.0.0:$(cat /etc/mamalista)
 					}
 				}
 				echo ""
 				echo -e "\033[1;32mINICIANDO O WEBSOCKET SECURITY\033[1;33m"
 				echo ""
-				fun_bar 'fun_iniWebSocket'
+				fun_bar 'fun_iniwssocks'
 				echo ""
 				echo -e "\033[1;32WEBSOCKET SECURITY ATIVADO COM SUCESSO\033[1;33m"
 				
@@ -1792,9 +1735,69 @@ elif [[ "$resposta" = '3.2' ]]; then
         
         fun_socks
     fi
-   			
+    		
+elif [[ "$resposta" = '5' ]]; then
+		clear
+		if ps x | grep -w cyberproxy | grep -v grep 1>/dev/null 2>/dev/null; then
+		echo -e "\E[41;1;37m           CYBER PROXY               \E[0m"
+				echo ""
+				fun_cyberproxy() { 
+					pkill cyberproxy
+					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+						screen -r -S "$cyberproxy" -X quit
+					done
+					[[ $(grep -wc "cyberproxy" /etc/autostart) != '0' ]] && {
+						sed -i '/cyberproxy/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O CYBER PROXY\033[1;33m"
+				echo ""
+				fun_bar 'fun_cyberproxy'
+				echo ""
+				echo -e "\033[1;32mCYBER PROXY DESATIVADO COM SUCESSO!\033[1;33m"
+				
+		fun_socks
+		else
+		echo -e "\E[44;1;37m           CYBER PROXY               \E[0m"
+				echo ""
+				rm -rf /etc/mamalista
+				read -p "$(echo -e "★ \033[1;32mQUAL PORTA ULTILIZAR? \033[1;37m")" -e -i 80 cuzin
+				echo "$cuzin" > /etc/mamalista
+				echo ""
+				read -p "$(echo -e "★ \033[1;32mQUAL MENSAGEM PARA STATUS? \033[1;37m")" -e -i CYBERPROXY cuzin2
+				rm -rf /etc/mamalista2
+				echo "$cuzin2" > /etc/mamalista2
+				[[ -z "cuzin" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					
+				fun_socks
+				}
+				verif_ptrs $porta
+				fun_inicyberproxy() {
+					sleep 1
+					screen -dmS cyberproxy /etc/SSHPlus/cyberproxy -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+					[[ $(grep -wc "cyberproxy" /etc/autostart) = '0' ]] && {
+						echo -e "screen -dmS cyberproxy /etc/SSHPlus/cyberproxy -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+					} || {
+						sed -i '/cyberproxy/d' /etc/autostart
+						echo -e "screen -dmS cyberproxy /etc/SSHPlus/cyberproxy -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O CYBER PROXY\033[1;33m"
+				echo ""
+				fun_bar 'fun_inicyberproxy'
+				echo ""
+				echo -e "\033[1;32CYBER PROXY ATIVADO COM SUCESSO\033[1;33m"
+				
+				fun_socks
+			fi			
+			
 						
-    elif [[ "$resposta" = '5' ]]; then
+elif [[ "$resposta" = '5.1' ]]; then
     clear
     if ps x | grep -w cyberproxy | grep -v grep 1>/dev/null 2>/dev/null; then
         echo -e "\E[41;1;37m             CYBER PROXY               \E[0m"
@@ -2114,7 +2117,7 @@ elif [[ "$resposta" = '3.2' ]]; then
 				echo -e "\033[1;32mALTERANDO STATUS!"
 				echo ""
 				fun_bar 'fun_msgsocks'
-                restartWebSocket() {
+                restartwssocks() {
                     if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 						echo -e "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_wssks
 						for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
@@ -2130,7 +2133,7 @@ elif [[ "$resposta" = '3.2' ]]; then
 				echo ""
 				echo -e "\033[1;32mREINICIANDO WEBSOCKET!"
 				echo ""
-				fun_bar 'restartWebSocket'
+				fun_bar 'restartwssocks'
 				echo ""
 				echo -e "\033[1;32mSTATUS ALTERADO COM SUCESSO!"
 				sleep 2
@@ -2333,7 +2336,7 @@ echo -e "\033[01;31m╚═══════════════════
 			}
 			
 			[[ "$(netstat -tlpn | grep 'cyberproxy' | wc -l)" != '0' ]] && {
-			echo -e "\033[01;31m\033[1;32mSERVICO: \033[1;33mCYBER PROXY \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'cyberproxy' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[01;31m\033[1;32mSERVICO: \033[1;33mCYBER PROXY \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'cyberproxy' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts4="\033[1;32m◉ "
 			} || {
 				sts4="\033[1;31m○ "
