Add files via upload

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -330,9 +330,9 @@ fun_squid
 		if netstat -nltp | grep 'dropbear' 1>/dev/null 2>/dev/null; then
 [[ $(netstat -nltp | grep -c 'dropbear') != '0' ]] && dpbr=$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs) || sqdp="\033[1;31mINDISPONIVEL"
 			if ps x | grep "limiter" | grep -v grep 1>/dev/null 2>/dev/null; then
-				stats='\033[1;32m✓ '
+				stats='\033[1;32m◉ '
 			else
-				stats='\033[1;31m✕ '
+				stats='\033[1;31m○ '
 			fi
 			echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 			echo -e "\033[0;34m┃\E[44;1;37m           GERENCIAR DROPBEAR            \E[0m\033[0;34m┃"
@@ -510,9 +510,9 @@ fun_squid
 			sks='\033[1;31mOFF'
 		}
 		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
-			chiselsts="\033[1;32m✓ "
+			chiselsts="\033[1;32m◉ "
 		} || {
-			chiselsts="\033[1;31m✕ "
+			chiselsts="\033[1;31m○ "
 		}
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHISEL $chiselsts \033[0m"
@@ -858,14 +858,14 @@ echo "Execulte como root"
 
 				opnp=$(cat /etc/openvpn/server.conf | grep "port" | awk {'print $2'})
 				[[ -d /var/www/html/openvpn ]] && {
-					ovpnweb=$(echo -e "\033[1;32m✓ ")
+					ovpnweb=$(echo -e "\033[1;32m◉ ")
 				} || {
-					ovpnweb=$(echo -e "\033[1;31m✕ ")
+					ovpnweb=$(echo -e "\033[1;31m○ ")
 				}
 				if grep "duplicate-cn" /etc/openvpn/server.conf >/dev/null; then
-					mult=$(echo -e "\033[1;32m✓ ")
+					mult=$(echo -e "\033[1;32m◉ ")
 				else
-					mult=$(echo -e "\033[1;31m✕ ")
+					mult=$(echo -e "\033[1;31m○ ")
 				fi
 				echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 				echo -e "\033[0;34m┃\E[44;1;37m            GERENCIAR OPENVPN            \E[0m\033[0;34m┃"
@@ -1481,22 +1481,22 @@ exit 0' >$RCLOCAL
     echo -e "\033[1;32mPORTAS (python)\033[1;31m: \033[1;37m$porta_python"
     }
 		
-		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m✓" || var_sks1="\033[1;31m✕"
-		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m✓" || var_sks2="\033[1;31m✕"
-		[[ $(screen -list | grep -wc 'proxydt') != '0' ]] && var_sks4="\033[1;32m✓" || var_sks4="\033[1;31m✕"
-		[[ $(screen -list | grep -wc 'security') != '0' ]] && var_sks3="\033[1;32m✓" || var_sks3="\033[1;31m✕"
-		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m✓" || sksop="\033[1;31m✕"
+		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m◉" || var_sks1="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m◉" || var_sks2="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'proxydt') != '0' ]] && var_sks4="\033[1;32m◉" || var_sks4="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'security') != '0' ]] && var_sks3="\033[1;32m◉" || var_sks3="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m◉" || sksop="\033[1;31m○"
 		
 		echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS SSH $var_sks1 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m02\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET $var_sks2 \033[0m                       \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m03\E[38;5;196m|\033[1;37m➜ \E[38;5;15mWEBSOCKET SECURITY $var_sks3 \033[0m              \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m04\E[38;5;196m|\033[1;37m➜ \E[38;5;15mPROXY DT $var_sks4 \033[0m                        \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m04\E[38;5;196m|\033[1;37m➜ \E[38;5;15mPROXY CP $var_sks4 \033[0m                        \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m05\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS OPENVPN $sksop \033[0m                   \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m06\E[38;5;196m|\033[1;37m➜ \E[38;5;15mABRIR PORTA\033[0m                        \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m07\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS SOCKS SSH\033[0m           \033[0;34m┃"
-		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m08\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS WEBSOCKET\033[0m           \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m05\E[38;5;196m|\033[1;37m➜ \E[38;5;15mPROXY CP $var_sks4 \033[0m                        \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m06\E[38;5;196m|\033[1;37m➜ \E[38;5;15mSOCKS OPENVPN $sksop \033[0m                   \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m07\E[38;5;196m|\033[1;37m➜ \E[38;5;15mABRIR PORTA\033[0m                        \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m08\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS SOCKS SSH\033[0m           \033[0;34m┃"
+		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m09a\E[38;5;196m|\033[1;37m➜ \E[38;5;15mALTERAR STATUS WEBSOCKET\033[0m           \033[0;34m┃"
 		echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m00\E[38;5;196m|\033[1;37m➜ \E[38;5;15mVOLTAR\033[0m                             \033[0;34m┃"
 		echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
 		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;37m?\033[1;31m?\033[1;37m : ";
@@ -1793,11 +1793,72 @@ elif [[ "$resposta" = '4' ]]; then
         
         fun_socks
     fi
+    
+    
+    elif [[ "$resposta" = '5' ]]; then
+		clear
+		if ps x | grep -w cyberproxy | grep -v grep 1>/dev/null 2>/dev/null; then
+		echo -e "\E[41;1;37m           CYBER PROXY               \E[0m"
+				echo ""
+				fun_cyberproxy() { 
+					pkill cyberproxy
+					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+						screen -r -S "$cyberproxy" -X quit
+					done
+					[[ $(grep -wc "cyberproxy" /etc/autostart) != '0' ]] && {
+						sed -i '/cyberproxy/d' /etc/autostart
+					}
+					sleep 1
+					screen -wipe >/dev/null
+				}
+				echo -e "\033[1;32mDESATIVANDO O CYBER PROXY\033[1;33m"
+				echo ""
+				fun_bar 'fun_cyberproxy'
+				echo ""
+				echo -e "\033[1;32mCYBER PROXY DESATIVADO COM SUCESSO!\033[1;33m"
+				
+		fun_socks
+		else
+		echo -e "\E[44;1;37m           CYBER PROXY               \E[0m"
+				echo ""
+				rm -rf /etc/mamalista
+				read -p "$(echo -e "★ \033[1;32mQUAL PORTA ULTILIZAR? \033[1;37m")" -e -i 80 cuzin
+				echo "$cuzin" > /etc/mamalista
+				echo ""
+				read -p "$(echo -e "★ \033[1;32mQUAL MENSAGEM PARA STATUS? \033[1;37m")" -e -i CYBERPROXY cuzin2
+				rm -rf /etc/mamalista2
+				echo "$cuzin2" > /etc/mamalista2
+				[[ -z "cuzin" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					
+				fun_socks
+				}
+				verif_ptrs $porta
+				fun_inicyberproxy() {
+					sleep 1
+					screen -dmS cyberproxy /etc/SSHPlus/cyberproxy -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+					[[ $(grep -wc "cyberproxy" /etc/autostart) = '0' ]] && {
+						echo -e "screen -dmS cyberproxy /etc/SSHPlus/cyberproxy -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+					} || {
+						sed -i '/cyberproxy/d' /etc/autostart
+						echo -e "screen -dmS cyberproxy /etc/SSHPlus/cyberproxy -proxy_port 0.0.0.0:$(cat /etc/mamalista)
+					}
+				}
+				echo ""
+				echo -e "\033[1;32mINICIANDO O CYBER PROXY\033[1;33m"
+				echo ""
+				fun_bar 'fun_inicyberproxy'
+				echo ""
+				echo -e "\033[1;32CYBER PROXY ATIVADO COM SUCESSO\033[1;33m"
+				
+				fun_socks
+			fi
 
 
 
 
-		elif [[ "$resposta" = '5' ]]; then
+		elif [[ "$resposta" = '6' ]]; then
 			if ps x | grep -w open.py | grep -v grep 1>/dev/null 2>/dev/null; then
 		echo -e "\E[41;1;37m            SOCKS OPENVPN             \E[0m"
 				echo ""
@@ -1856,7 +1917,7 @@ elif [[ "$resposta" = '4' ]]; then
 			fi
 
 
-		elif [[ "$resposta" = '6' ]]; then
+		elif [[ "$resposta" = '7' ]]; then
 			if ps x | grep proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 				sockspt=$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)
 		echo -e "\E[44;1;37m            PROXY SOCKS             \E[0m"
@@ -1983,7 +2044,7 @@ elif [[ "$resposta" = '4' ]]; then
 				sleep 2
 				fun_socks
 			fi
-		elif [[ "$resposta" = '8' ]]; then
+		elif [[ "$resposta" = '9' ]]; then
 			if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
 		msgsocks=$(cat /etc/SSHPlus/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
 				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
@@ -2076,7 +2137,7 @@ elif [[ "$resposta" = '4' ]]; then
 				sleep 2
 				fun_socks
 			fi
-		elif [[ "$resposta" = '00' ]]; then
+		elif [[ "$resposta" = '0' ]]; then
 			
 			clear
 			fun_conexao
@@ -2214,89 +2275,96 @@ echo -e "\E[41;1;37m             REMOVER O SSLH               \E[0m\n"
 echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 			echo -e "\033[0;34m┃\E[44;1;37m             MODO DE CONEXAO             \E[0m\033[0;34m┃"
 			echo -e "\033[0;34m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛\033[0m"
-			echo -e "\033[1;32mOPENSSH\033[1;31m: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m✓ "
+			echo -e "\033[1;32mOPENSSH\033[1;31m: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
 			[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mCHISEL\033[1;32m: \033[1;37m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts8="\033[1;32m✓ "
+				sts8="\033[1;32m◉ "
 			} || {
-				sts8="\033[1;31m✕ "
+				sts8="\033[1;31m○ "
 			}
 			[[ "$(ps x | grep 'slowdns' | grep -v 'grep' | wc -l)" != '0' ]] && {
-				sts9="\033[1;32m✓ "
+				sts9="\033[1;32m◉ "
 			} || {
-				sts9="\033[1;31m✕ "
+				sts9="\033[1;31m○ "
 			}
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSSLH\033[1;31m: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts7="\033[1;32m✓ "
+				sts7="\033[1;32m◉ "
 			} || {
-				sts7="\033[1;31m✕ "
+				sts7="\033[1;31m○ "
 			}
 
 			[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mOPENVPN\033[1;31m: \033[1;37m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts5="\033[1;32m✓ "
+				sts5="\033[1;32m◉ "
 			} || {
-				sts5="\033[1;31m✕ "
+				sts5="\033[1;31m○ "
 			}
 			
 			[[ "$(netstat -tlpn | grep 'WebSocket' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;33m ATIVADO!\033[1;37m$(netstat -nplt | grep 'WebSocket' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts4="\033[1;32m✓ "
+				sts4="\033[1;32m◉ "
 			} || {
-				sts4="\033[1;31m✕ "
+				sts4="\033[1;31m○ "
 			}
 			
 			[[ "$(netstat -tlpn | grep 'security' | wc -l)" != '0' ]] && {
     porta_security=$(netstat -nplt | grep -w 'security' | awk '{split($4,a,":"); print a[length(a)]}')
     echo -e "\033[1;32mWEBSOCKET SECURITY\033[1;31m: \033[1;37m$porta_security"
-    sts4="\033[1;32m✓ "
+    sts4="\033[1;32m◉ "
 } || {
-    sts4="\033[1;31m✕ "
+    sts4="\033[1;31m○ "
 }
 			
 			[[ "$(netstat -tlpn | grep 'proxydt' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mPROXY DT\033[1;31m: \033[1;37m$(netstat -nplt | grep 'proxydt' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts4="\033[1;32m✓ "
+				sts4="\033[1;32m◉ "
 			} || {
-				sts4="\033[1;31m✕ "
+				sts4="\033[1;31m○ "
+			}
+			
+			[[ "$(netstat -tlpn | grep 'cyberproxy' | wc -l)" != '0' ]] && {
+				echo -e "\033[01;31m\033[1;32mSERVICO: \033[1;33mCYBER PROXY \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'cyberproxy' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				sts4="\033[1;32m◉ "
+			} || {
+				sts4="\033[1;31m○ "
 			}
 
 			[[ "$(netstat -tlpn | grep -E 'python|proxydt|security' | wc -l)" != '0' ]] && {
     echo -e "\033[1;32mPROXY SOCKS PORTAS ATIVADAS\033[1;31m: \033[1;37m$(netstat -nplt | grep -E 'python|proxydt|security' | awk '{print $4}' | cut -d: -f2 | xargs)"
-    sts4="\033[1;32m✓ "
+    sts4="\033[1;32m◉ "
 } || {
-    sts4="\033[1;31m✕ "
+    sts4="\033[1;31m○ "
 }
 			
 			
 			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
 				echo -e "\033[1;32mSSL TUNNEL\033[1;31m: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
-				sts3="\033[1;32m✓ "
+				sts3="\033[1;32m◉ "
 			} || {
-				sts3="\033[1;31m✕ "
+				sts3="\033[1;31m○ "
 			}
 			[[ "$(netstat -tlpn | grep 'dropbear' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mDROPBEAR\033[1;31m: \033[1;37m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
-				sts2="\033[1;32m✓ "
+				sts2="\033[1;32m◉ "
 			} || {
-				sts2="\033[1;31m✕ "
+				sts2="\033[1;31m○ "
 			}
 			[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSQUID\033[1;31m: \033[1;37m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
-				sts1="\033[1;32m✓ "
+				sts1="\033[1;32m◉ "
 			} || {
-				sts1="\033[1;31m✕ "
+				sts1="\033[1;31m○ "
 			}
 			[[ "$(netstat -tunlp | grep 'trojan-go' | wc -l)" != '0' ]] && {
-				trojansts="\033[1;32m✓ "
+				trojansts="\033[1;32m◉ "
 			} || {
-				trojansts="\033[1;31m✕ "
+				trojansts="\033[1;31m○ "
 			}
 			[[ "$(netstat -tunlp | grep 'v2ray' | wc -l)" != '0' ]] && {
-				xv2ray="\033[1;32m✓ "
+				xv2ray="\033[1;32m◉ "
 			} || {
-				xv2ray="\033[1;31m✕ "
+				xv2ray="\033[1;31m○ "
 			}
 			echo -e "\033[0;34m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\033[0m"
 			echo -e "\033[0;34m┃\E[38;5;196m|\E[38;5;33m01\E[38;5;196m|\033[1;37m➜ \E[38;5;15mOPENSSH $sts6                         \033[0;34m┃"
